USE evaluasi_kurikulum;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE jawaban_multi; TRUNCATE TABLE jawaban; TRUNCATE TABLE pengisian_matkul; TRUNCATE TABLE pengisian; TRUNCATE TABLE opsi_pertanyaan; TRUNCATE TABLE pertanyaan; TRUNCATE TABLE mata_kuliah_bk; TRUNCATE TABLE mata_kuliah; TRUNCATE TABLE bahan_kajian; TRUNCATE TABLE kategori_kompetensi; TRUNCATE TABLE periode_evaluasi; TRUNCATE TABLE profil_pengguna; TRUNCATE TABLE pengguna;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO pengguna (id, nama, email, password_hash, peran) VALUES
(1, 'Administrator Prodi', 'admin@machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'admin'),
(2, 'Carlo Imanuel Suryahasilaga', '322310001@student.machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'mahasiswa'),
(3, 'William Christopher Linardi', '322310020@student.machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'mahasiswa'),
(4, 'Kurniawan Michael Bimantara', '322310013@student.machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'mahasiswa'),
(5, 'Marcell Chandra Kenchana', '322310015@student.machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'mahasiswa'),
(6, 'Daniel Saputra', 'daniel.saputra@machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'dosen'),
(7, 'Budi Santoso', 'budi.santoso@machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'dosen'),
(8, 'Siti Aminah', 'siti.aminah@machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'dosen'),
(9, 'Rina Wijaya', 'rina.wijaya@machung.ac.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'dosen'),
(10, 'Andi Gunawan', 'andi.alumni@gmail.com', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'alumni'),
(11, 'Reza Pratama', 'reza.alumni@yahoo.com', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'alumni'),
(12, 'Maya Sari', 'maya.alumni@hotmail.com', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'alumni'),
(13, 'Kevin Sanjaya', 'kevin.alumni@gmail.com', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'alumni'),
(14, 'HRD PT Teknologi Maju', 'hrd@tekmaju.com', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'perusahaan'),
(15, 'Recruiter Tokopedia', 'recruiter@tokopedia.com', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'perusahaan'),
(16, 'Talent Gojek', 'talent@gojek.com', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'perusahaan'),
(17, 'HR Bank BCA', 'hr@bca.co.id', '$2y$10$h412JiSNLScjfMjlAIS6beOg643fBa6Vy3EljKyZGs0R57LRsivOO', 'perusahaan');

INSERT INTO profil_pengguna (pengguna_id, nomor_induk, tahun_lulus, instansi) VALUES
(1, 'ADM-001', NULL, 'Universitas Ma Chung'),
(2, '322310001', NULL, 'Universitas Ma Chung'),
(3, '322310020', NULL, 'Universitas Ma Chung'),
(4, '322310013', NULL, 'Universitas Ma Chung'),
(5, '322310015', NULL, 'Universitas Ma Chung'),
(6, '0712038401', NULL, 'Universitas Ma Chung'),
(7, '0712038402', NULL, 'Universitas Ma Chung'),
(8, '0712038403', NULL, 'Universitas Ma Chung'),
(9, '0712038404', NULL, 'Universitas Ma Chung'),
(10, NULL, 2021, 'PT Teknologi Maju'),
(11, NULL, 2022, 'Tokopedia'),
(12, NULL, 2020, 'Gojek'),
(13, NULL, 2023, 'Bank BCA'),
(14, NULL, NULL, 'PT Teknologi Maju'),
(15, NULL, NULL, 'Tokopedia'),
(16, NULL, NULL, 'Gojek'),
(17, NULL, NULL, 'Bank BCA');

INSERT INTO periode_evaluasi (id, tahun_akademik, status) VALUES
(1, '2024/2025 Genap', 'tutup'),
(2, '2025/2026 Ganjil', 'buka');

INSERT INTO kategori_kompetensi (id, nama, deskripsi) VALUES
(1, 'K1 Data, Analitik & Kecerdasan Buatan', 'Pengelolaan data, analitik bisnis, data science, dan kecerdasan buatan.'),
(2, 'K2 Enterprise Systems & Transformasi Bisnis', 'Sistem ERP, arsitektur enterprise, e-bisnis, dan inovasi digital.'),
(3, 'K3 Rekayasa Perangkat Lunak & Pengembangan Aplikasi', 'Analisis kebutuhan, perancangan, pemrograman, pengujian, dan antarmuka pengguna.'),
(4, 'K4 Infrastruktur, Jaringan & Keamanan Siber', 'Infrastruktur TI, jaringan, dan keamanan sistem.'),
(5, 'K5 Manajemen Proyek, Tata Kelola & Audit TI', 'Manajemen proyek, strategi, risiko, layanan, dan audit TI.');

INSERT INTO bahan_kajian (id, kode, nama_id, nama_en, kategori_kompetensi_id) VALUES
(1, 'BK01', 'Dasar-dasar Sistem Informasi', 'Foundation of Information Systems', NULL),
(2, 'BK02', 'Manajemen Data dan Informasi', 'Data / Information Management', 1),
(3, 'BK03', 'Infrastruktur TI', 'IT Infrastructure', 4),
(4, 'BK04', 'Manajemen Proyek SI', 'IS Project Management', 5),
(5, 'BK05', 'Analisis dan Perancangan Sistem', 'Systems Analysis & Design', 3),
(6, 'BK06', 'Manajemen dan Strategi SI', 'IS Management and Strategy', 5),
(7, 'BK07', 'Pengembangan Aplikasi / Pemrograman', 'Application Development / Programming', 3),
(8, 'BK08', 'Keamanan Komputasi', 'Secure Computing', 4),
(9, 'BK09', 'Etika, Penggunaan, dan Dampak bagi Masyarakat', 'Ethics, use and implications for society', NULL),
(10, 'BK10', 'Praktikum', 'Praktikum', NULL),
(11, 'BK11', 'Matematika dan Statistika', 'Mathematics and statistics', 1),
(12, 'BK12', 'Analitik Data / Bisnis', 'Data / Business Analytics', 1),
(13, 'BK13', 'Arsitektur Enterprise', 'Enterprise Architecture', 2),
(14, 'BK14', 'Perancangan Antarmuka Pengguna', 'User Interface Design', 3),
(15, 'BK15', 'Inovasi Digital', 'Digital Innovation', 2);

INSERT INTO mata_kuliah (id, kode, nama, sks, semester, jenis, kelompok, aktif) VALUES
(1, 'SSI1140', 'Konsep dan Pengantar SI/TI', 3, 1, 'wajib', 'prodi', 1),
(2, 'SSI1141', 'Antar Muka dan Pengalaman Pengguna', 3, 1, 'wajib', 'prodi', 1),
(3, 'SSI1142', 'Konsep Basis Data', 3, 1, 'wajib', 'prodi', 1),
(4, 'SSI1143', 'Matematika Diskrit', 3, 1, 'wajib', 'prodi', 1),
(5, 'SSI1144', 'Algoritma dan Pengantar Pemrograman', 2, 1, 'wajib', 'prodi', 1),
(6, 'SSI1145', 'Praktikum Algoritma dan Pengantar Pemrograman', 1, 1, 'wajib', 'prodi', 1),
(7, 'SSI1146', 'Desain dan Manajemen Proses Bisnis', 3, 1, 'wajib', 'prodi', 1),
(8, 'SSI1240', 'Bahasa Pemrograman', 2, 2, 'wajib', 'prodi', 1),
(9, 'SSI1241', 'Praktikum Bahasa Pemrograman', 1, 2, 'wajib', 'prodi', 1),
(10, 'SSI1242', 'Sistem dan Administrasi Basis Data', 3, 2, 'wajib', 'prodi', 1),
(11, 'SSI1243', 'Analisa dan Kebutuhan Perangkat Lunak', 3, 2, 'wajib', 'prodi', 1),
(12, 'SSI1244', 'Manajemen dan Proses TI', 3, 2, 'wajib', 'prodi', 1),
(13, 'SSI1245', 'Pengantar Akuntansi dan Keuangan', 3, 2, 'wajib', 'prodi', 1),
(14, 'SSI2140', 'Statistika dan Probabilitas', 2, 3, 'wajib', 'prodi', 1),
(15, 'SSI2141', 'Praktikum Statistika dan Probabilitas', 1, 3, 'wajib', 'prodi', 1),
(16, 'SSI2142', 'Arsitektur Enterprise', 3, 3, 'wajib', 'prodi', 1),
(17, 'SSI2143', 'Enterprise System', 5, 3, 'wajib', 'prodi', 1),
(18, 'SSI2144', 'Desain dan Deskripsi Perangkat Lunak', 3, 3, 'wajib', 'prodi', 1),
(19, 'SSI2145', 'Perencanaan Strategis SI/TI', 3, 3, 'wajib', 'prodi', 1),
(20, 'SSI2146', 'E-Bisnis', 3, 3, 'wajib', 'prodi', 1),
(21, 'SSI2240', 'Manajemen Proyek Sistem Informasi', 3, 4, 'wajib', 'prodi', 1),
(22, 'SSI2241', 'Sistem Informasi Manajemen', 3, 4, 'wajib', 'prodi', 1),
(23, 'SSI2242', 'Manajemen Resiko SI/TI', 3, 4, 'wajib', 'prodi', 1),
(24, 'SSI2243', 'Keamanan Sistem Informasi', 3, 4, 'wajib', 'prodi', 1),
(25, 'SSI2244', 'Kecerdasan Bisnis', 3, 4, 'wajib', 'prodi', 1),
(26, 'SSI2245', 'Manajemen Layanan Teknologi Informasi', 3, 4, 'wajib', 'prodi', 1),
(27, 'SSI2246', 'Manajemen & Organisasi', 2, 4, 'wajib', 'prodi', 1),
(28, 'SSI3140', 'Pemrograman Bergerak', 2, 5, 'wajib', 'prodi', 1),
(29, 'SSI3141', 'Praktikum Pemrograman Bergerak', 1, 5, 'wajib', 'prodi', 1),
(30, 'SSI3142', 'Transformasi Digital', 2, 5, 'wajib', 'prodi', 1),
(31, 'SSI3143', 'Testing dan Dokumentasi Perangkat Lunak', 3, 5, 'wajib', 'prodi', 1),
(32, 'SSI3144', 'Audit SI/TI', 3, 5, 'wajib', 'prodi', 1),
(33, 'SSI3145', 'Metodologi Penelitian dan Penulisan Ilmiah', 2, 5, 'wajib', 'prodi', 1),
(34, 'SSI3146', 'Teknologi Keuangan', 3, 5, 'wajib', 'prodi', 1),
(35, 'SSI3240', 'Desain dan Keamanan Jaringan', 3, 6, 'wajib', 'prodi', 1),
(36, 'SSI3241', 'Komunikasi dan Negosiasi', 2, 6, 'wajib', 'prodi', 1),
(37, 'SSI3244', 'Manajemen Data', 3, 6, 'wajib', 'prodi', 1),
(38, 'SSI3242', 'Etika Profesi dan Profesional', 2, 6, 'wajib', 'prodi', 1),
(39, 'SSI3245', 'Pengukuran dan Kualitas Perangkat Lunak', 3, 6, 'wajib', 'prodi', 1),
(40, 'SSI4140', 'Proyek Pengembangan Sistem Informasi', 3, 7, 'wajib', 'prodi', 1),
(41, 'SSI4141', 'Kerja Praktek / Magang', 3, 7, 'wajib', 'prodi', 1),
(42, 'SSI4143', 'Technopreneurship', 3, 7, 'wajib', 'prodi', 1),
(43, 'SSI4144', 'Sistem Informasi Akuntansi', 3, 7, 'wajib', 'prodi', 1),
(44, 'SSI4240', 'Tugas Akhir / Skripsi', 6, 8, 'wajib', 'prodi', 1),
(45, 'SSI5130', 'Sistem Informasi Geografis', 3, 7, 'pilihan', 'prodi', 1),
(46, 'SSI5131', 'Kualitas Data', 3, 7, 'pilihan', 'prodi', 1),
(47, 'SSI5132', 'Sistem Informasi Manufaktur', 3, 7, 'pilihan', 'prodi', 1),
(48, 'MPK403', 'Bahasa Inggris 1', 1, 1, 'wajib', 'universitas', 1),
(49, 'MPK404', 'Bahasa Inggris 2', 1, 2, 'wajib', 'universitas', 1);

INSERT INTO mata_kuliah_bk (mata_kuliah_id, bahan_kajian_id, utama) VALUES
(1, 1, 0),
(2, 14, 0),
(3, 2, 0),
(4, 11, 0),
(5, 7, 0),
(6, 10, 0),
(7, 5, 0),
(8, 7, 0),
(9, 10, 0),
(10, 2, 0),
(11, 5, 0),
(12, 6, 0),
(13, 9, 0),
(14, 11, 0),
(15, 10, 0),
(16, 13, 0),
(17, 13, 0),
(18, 5, 0),
(19, 6, 0),
(20, 15, 0),
(21, 4, 0),
(22, 6, 0),
(23, 6, 0),
(24, 8, 0),
(25, 12, 0),
(26, 6, 0),
(27, 9, 0),
(28, 7, 0),
(29, 10, 0),
(30, 6, 0),
(31, 5, 0),
(32, 6, 0),
(33, 10, 0),
(34, 15, 0),
(35, 3, 1),
(35, 8, 0),
(36, 9, 0),
(37, 2, 0),
(38, 9, 0),
(39, 5, 0),
(40, 4, 0),
(41, 10, 0),
(42, 15, 0),
(43, 10, 0),
(44, 10, 0),
(45, 2, 0),
(46, 7, 0),
(47, 9, 0);

INSERT INTO pertanyaan (id, kode, teks, bantuan, tipe, bagian, peran_sasaran, wajib, label_skala, syarat_tampil, penanda, maks_pilihan, urutan, default_aktif) VALUES
(1, 'A1', 'Mata kuliah ini layak dipertahankan dalam kurikulum program studi.', 'Nilai 1 atau 2 memerlukan alasan.', 'skala', 'matkul', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, 'untuk_peringkat', NULL, 1, 1),
(2, 'A1', 'Mata kuliah ini layak dipertahankan dalam kurikulum program studi.', 'Nilai 1 atau 2 memerlukan alasan.', 'skala', 'matkul', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, 'untuk_peringkat', NULL, 1, 1),
(3, 'A1', 'Mata kuliah ini layak dipertahankan dalam kurikulum program studi.', 'Nilai 1 atau 2 memerlukan alasan.', 'skala', 'matkul', 'perusahaan', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, 'untuk_peringkat', NULL, 1, 1),
(4, 'A1', 'Mata kuliah ini layak dipertahankan dalam kurikulum program studi.', 'Nilai 1 atau 2 memerlukan alasan.', 'skala', 'matkul', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, 'untuk_peringkat', NULL, 1, 1),
(5, 'A2', 'Seberapa mudah materi mata kuliah ini untuk dipahami?', 'Nilai berdasarkan penjelasan, bahan ajar, dan tugas.', 'skala', 'matkul', 'mahasiswa', 1, '[\"Sangat sulit\", \"Sulit\", \"Cukup\", \"Mudah\", \"Sangat mudah\"]', NULL, NULL, NULL, 2, 1),
(6, 'A3', 'Beban materi dan tugas pada mata kuliah ini sebanding dengan bobot SKS-nya.', NULL, 'skala', 'matkul', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 3, 1),
(7, 'A4', 'Setelah mengikuti mata kuliah ini, saya memahami konsep dasar bidangnya.', NULL, 'skala', 'matkul', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 4, 1),
(8, 'A5', 'Mata kuliah ini membantu saya mengikuti mata kuliah lanjutan.', 'Pilih Netral bila Anda belum mengambil mata kuliah lanjutannya.', 'skala', 'matkul', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 5, 1),
(9, 'A6', 'Saran atau catatan Anda untuk mata kuliah ini.', 'Misalnya bagian yang terasa terlalu sulit atau terlalu mudah.', 'teks', 'matkul', 'mahasiswa', 0, NULL, NULL, NULL, NULL, 6, 1),
(10, 'A2', 'Seberapa berguna materi mata kuliah ini dalam pekerjaan Anda saat ini?', 'Nilai berdasarkan pengalaman kerja, bukan kesan saat kuliah.', 'skala', 'matkul', 'alumni', 1, '[\"Tidak berguna\", \"Kurang berguna\", \"Cukup berguna\", \"Berguna\", \"Sangat berguna\"]', NULL, NULL, NULL, 2, 1),
(11, 'A3', 'Seberapa sering Anda menggunakan materi mata kuliah ini dalam pekerjaan?', NULL, 'skala', 'matkul', 'alumni', 1, '[\"Tidak pernah\", \"Jarang\", \"Kadang-kadang\", \"Sering\", \"Sangat sering\"]', NULL, NULL, NULL, 3, 1),
(12, 'A4', 'Kedalaman materi mata kuliah ini cukup sebagai bekal bekerja.', NULL, 'skala', 'matkul', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 4, 1),
(13, 'A5', 'Materi mata kuliah ini sejalan dengan praktik yang berlaku di tempat kerja Anda.', NULL, 'skala', 'matkul', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 5, 1),
(14, 'A6', 'Saran atau catatan Anda untuk mata kuliah ini.', 'Misalnya materi yang perlu ditambah atau dikurangi.', 'teks', 'matkul', 'alumni', 0, NULL, NULL, NULL, NULL, 6, 1),
(15, 'A2', 'Seberapa sesuai bidang yang dicakup mata kuliah ini dengan kebutuhan kerja di perusahaan Anda saat ini?', 'Bila nama mata kuliahnya kurang dikenal, gunakan keterangan Bahan Kajian pada kartu.', 'skala', 'matkul', 'perusahaan', 1, '[\"Tidak sesuai\", \"Kurang sesuai\", \"Cukup sesuai\", \"Sesuai\", \"Sangat sesuai\"]', NULL, NULL, NULL, 2, 1),
(16, 'A3', 'Lulusan yang menguasai bidang ini lebih siap bekerja di perusahaan kami.', NULL, 'skala', 'matkul', 'perusahaan', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 3, 1),
(17, 'A4', 'Bidang ini tetap dibutuhkan perusahaan kami dalam 3 sampai 5 tahun ke depan.', NULL, 'skala', 'matkul', 'perusahaan', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 4, 1),
(18, 'A5', 'Bagaimana sebaiknya porsi bidang ini dalam kurikulum?', NULL, 'pilihan_ganda', 'matkul', 'perusahaan', 1, NULL, NULL, NULL, NULL, 5, 1),
(19, 'A6', 'Keahlian terkait yang menurut Anda belum tercakup oleh mata kuliah ini.', NULL, 'teks', 'matkul', 'perusahaan', 0, NULL, NULL, NULL, NULL, 6, 1),
(20, 'A2', 'Seberapa mutakhir silabus dan materi mata kuliah ini dibandingkan kebutuhan industri saat ini?', 'Bandingkan dengan perkembangan teknologi dan praktik industri terbaru.', 'skala', 'matkul', 'dosen', 1, '[\"Sangat tertinggal\", \"Tertinggal\", \"Cukup mutakhir\", \"Mutakhir\", \"Sangat mutakhir\"]', NULL, NULL, NULL, 2, 1),
(21, 'A3', 'Mata kuliah ini saat ini berbobot {sks} SKS. Bagaimana rekomendasi Anda terhadap bobot SKS dan durasinya?', 'Pertimbangkan kedalaman materi dan jam tatap muka.', 'pilihan_ganda', 'matkul', 'dosen', 1, NULL, NULL, NULL, NULL, 3, 1),
(22, 'A4', 'Berapa usulan bobot atau pembagian semesternya, dan apa alasannya?', NULL, 'teks', 'matkul', 'dosen', 0, NULL, 'A3_BUKAN_OPSI_1', NULL, NULL, 4, 1),
(23, 'A5', 'Materi mata kuliah ini selaras dengan capaian pembelajaran dan mata kuliah lanjutannya.', NULL, 'skala', 'matkul', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 5, 1),
(24, 'A6', 'Mahasiswa umumnya memiliki bekal awal yang cukup untuk mengikuti mata kuliah ini.', NULL, 'skala', 'matkul', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 6, 1),
(25, 'A7', 'Bab, teori, atau studi kasus yang sebaiknya diperbarui atau dihapus.', 'Boleh dikosongkan bila materi sudah sesuai.', 'teks', 'matkul', 'dosen', 0, NULL, NULL, NULL, NULL, 7, 1),
(26, 'AX1', 'Menurut Anda, posisi semester mata kuliah ini sudah tepat?', NULL, 'pilihan_ganda', 'matkul', 'mahasiswa', 1, NULL, NULL, NULL, NULL, 90, 0),
(27, 'AX1', 'Menurut Anda, posisi semester mata kuliah ini sudah tepat?', NULL, 'pilihan_ganda', 'matkul', 'alumni', 1, NULL, NULL, NULL, NULL, 90, 0),
(28, 'AX1', 'Menurut Anda, posisi semester mata kuliah ini sudah tepat?', NULL, 'pilihan_ganda', 'matkul', 'dosen', 1, NULL, NULL, NULL, NULL, 90, 0),
(29, 'AX2', 'Bagaimana status mata kuliah ini sebaiknya dalam kurikulum?', NULL, 'pilihan_ganda', 'matkul', 'mahasiswa', 1, NULL, NULL, NULL, NULL, 91, 0),
(30, 'AX2', 'Bagaimana status mata kuliah ini sebaiknya dalam kurikulum?', NULL, 'pilihan_ganda', 'matkul', 'alumni', 1, NULL, NULL, NULL, NULL, 91, 0),
(31, 'AX2', 'Bagaimana status mata kuliah ini sebaiknya dalam kurikulum?', NULL, 'pilihan_ganda', 'matkul', 'perusahaan', 1, NULL, NULL, NULL, NULL, 91, 0),
(32, 'AX2', 'Bagaimana status mata kuliah ini sebaiknya dalam kurikulum?', NULL, 'pilihan_ganda', 'matkul', 'dosen', 1, NULL, NULL, NULL, NULL, 91, 0),
(33, 'B1', 'Seberapa mudah Anda beradaptasi dengan cara dan beban belajar di program studi ini?', 'Pikirkan pengalaman Anda secara keseluruhan.', 'skala', 'kompetensi', 'mahasiswa', 1, '[\"Sangat sulit\", \"Sulit\", \"Cukup\", \"Mudah\", \"Sangat mudah\"]', NULL, NULL, NULL, 1, 1),
(34, 'B2', 'Urutan mata kuliah dari semester ke semester membantu saya memahami materi secara bertahap.', NULL, 'skala', 'kompetensi', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 2, 1),
(35, 'B3', 'Kurikulum menyeimbangkan teori dan praktik dengan baik.', NULL, 'skala', 'kompetensi', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 3, 1),
(36, 'B4', 'Kurikulum membantu saya menyiapkan diri untuk bekerja di bidang SI/TI.', NULL, 'skala', 'kompetensi', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 4, 1),
(37, 'B5', 'Saya memahami keterkaitan antar mata kuliah di program studi ini.', NULL, 'skala', 'kompetensi', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 5, 1),
(38, 'B6', 'Beban belajar per semester (jumlah SKS dan tugas) masih dapat saya tangani.', NULL, 'skala', 'kompetensi', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 6, 1),
(39, 'B7', 'Saya percaya diri dengan kemampuan teknis yang saya peroleh sejauh ini.', NULL, 'skala', 'kompetensi', 'mahasiswa', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 7, 1),
(40, 'B8', 'Bidang kompetensi mana yang paling ingin Anda perdalam?', 'Pilih paling banyak 2.', 'pilihan_ganda_banyak', 'kompetensi', 'mahasiswa', 1, NULL, NULL, NULL, 2, 8, 1),
(41, 'B9', 'Mata kuliah atau topik yang menurut Anda perlu ditambahkan ke kurikulum.', NULL, 'teks', 'kompetensi', 'mahasiswa', 0, NULL, NULL, NULL, NULL, 9, 1),
(42, 'B10', 'Saran lain untuk kurikulum program studi.', NULL, 'teks', 'kompetensi', 'mahasiswa', 0, NULL, NULL, NULL, NULL, 10, 1),
(43, 'B1', 'Secara keseluruhan, seberapa relevan kurikulum program studi dengan tuntutan pekerjaan Anda saat ini?', 'Pikirkan seluruh bekal yang Anda dapat selama kuliah.', 'skala', 'kompetensi', 'alumni', 1, '[\"Sangat tidak relevan\", \"Kurang relevan\", \"Cukup relevan\", \"Relevan\", \"Sangat relevan\"]', NULL, NULL, NULL, 1, 1),
(44, 'B2', 'Bekal kemampuan teknis (hardskill) dari kampus cukup untuk memulai pekerjaan pertama saya.', NULL, 'skala', 'kompetensi', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 2, 1),
(45, 'B3', 'Bekal kemampuan non-teknis (softskill) dari kampus cukup untuk memulai pekerjaan pertama saya.', NULL, 'skala', 'kompetensi', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 3, 1),
(46, 'B4', 'Saya dapat beradaptasi dengan cepat di lingkungan kerja berkat bekal dari kampus.', NULL, 'skala', 'kompetensi', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 4, 1),
(47, 'B5', 'Kurikulum memberi dasar yang kuat bagi saya untuk terus mempelajari teknologi baru.', NULL, 'skala', 'kompetensi', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 5, 1),
(48, 'B6', 'Kerja praktik, magang, dan proyek selama kuliah membantu kesiapan kerja saya.', NULL, 'skala', 'kompetensi', 'alumni', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 6, 1),
(49, 'B7', 'Kelompok kompetensi apa yang paling sering Anda gunakan dalam pekerjaan?', 'Pilih paling banyak 2 yang paling dominan.', 'pilihan_ganda_banyak', 'kompetensi', 'alumni', 1, NULL, NULL, 'WARNA_PRODI', 2, 7, 1),
(50, 'B8', 'Materi yang dulu terasa kurang penting, tetapi ternyata berguna di dunia kerja.', 'Sebutkan materi atau mata kuliahnya.', 'teks', 'kompetensi', 'alumni', 0, NULL, NULL, NULL, NULL, 8, 1),
(51, 'B9', 'Teknologi atau materi yang menurut Anda sudah usang dan perlu diperbarui.', NULL, 'teks', 'kompetensi', 'alumni', 0, NULL, NULL, NULL, NULL, 9, 1),
(52, 'B10', 'Saran lain untuk kurikulum program studi.', NULL, 'teks', 'kompetensi', 'alumni', 0, NULL, NULL, NULL, NULL, 10, 1),
(53, 'B1', 'Seberapa puas Anda dengan kemampuan teknis (hardskill) lulusan program studi kami?', 'Nilai berdasarkan lulusan yang Anda ketahui langsung.', 'skala', 'kompetensi', 'perusahaan', 1, '[\"Sangat tidak puas\", \"Tidak puas\", \"Cukup puas\", \"Puas\", \"Sangat puas\"]', NULL, NULL, NULL, 1, 1),
(54, 'B2', 'Bagaimana penilaian Anda terhadap kemampuan non-teknis (softskill) lulusan kami, seperti komunikasi, inisiatif, etika, dan kerja sama tim?', NULL, 'skala', 'kompetensi', 'perusahaan', 1, '[\"Sangat kurang\", \"Kurang\", \"Cukup\", \"Baik\", \"Sangat baik\"]', NULL, NULL, NULL, 2, 1),
(55, 'B3', 'Lulusan kami mampu beradaptasi dengan cepat di lingkungan kerja.', NULL, 'skala', 'kompetensi', 'perusahaan', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 3, 1),
(56, 'B4', 'Lulusan kami menguasai dasar-dasar SI/TI yang dibutuhkan perusahaan.', NULL, 'skala', 'kompetensi', 'perusahaan', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 4, 1),
(57, 'B5', 'Lulusan kami mampu menjembatani kebutuhan bisnis dan solusi teknologi.', NULL, 'skala', 'kompetensi', 'perusahaan', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 5, 1),
(58, 'B6', 'Bagaimana kemampuan lulusan kami mempelajari teknologi baru di tempat kerja?', NULL, 'skala', 'kompetensi', 'perusahaan', 1, '[\"Sangat kurang\", \"Kurang\", \"Cukup\", \"Baik\", \"Sangat baik\"]', NULL, NULL, NULL, 6, 1),
(59, 'B7', 'Kompetensi apa yang paling Anda butuhkan dari lulusan IT dalam beberapa tahun ke depan?', 'Pilih paling banyak 2 yang paling Anda prioritaskan. Jawaban ini membentuk arah kurikulum program studi.', 'pilihan_ganda_banyak', 'kompetensi', 'perusahaan', 1, NULL, NULL, 'WARNA_PRODI', 2, 7, 1),
(60, 'B8', 'Kesenjangan kompetensi (skill gap) yang paling nyata pada lulusan kami saat mulai bekerja.', 'Sebutkan contoh yang Anda temui.', 'teks', 'kompetensi', 'perusahaan', 0, NULL, NULL, NULL, NULL, 8, 1),
(61, 'B9', 'Perangkat lunak, framework, atau standar yang sebaiknya diajarkan agar lulusan langsung siap pakai di perusahaan Anda.', 'Sebutkan nama spesifiknya.', 'teks', 'kompetensi', 'perusahaan', 0, NULL, NULL, NULL, NULL, 9, 1),
(62, 'B10', 'Masukan lain untuk kurikulum program studi.', NULL, 'teks', 'kompetensi', 'perusahaan', 0, NULL, NULL, NULL, NULL, 10, 1),
(63, 'B1', 'Kurikulum program studi saat ini selaras dengan perkembangan kebutuhan industri.', NULL, 'skala', 'kompetensi', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 1, 1),
(64, 'B2', 'Capaian pembelajaran lulusan sudah tercermin dalam rangkaian mata kuliah.', NULL, 'skala', 'kompetensi', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 2, 1),
(65, 'B3', 'Urutan mata kuliah antar semester sudah logis dan bertahap.', NULL, 'skala', 'kompetensi', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 3, 1),
(66, 'B4', 'Keseimbangan antara teori dan praktik dalam kurikulum sudah baik.', NULL, 'skala', 'kompetensi', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 4, 1),
(67, 'B5', 'Tidak ada tumpang tindih materi yang berarti antar mata kuliah.', NULL, 'skala', 'kompetensi', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 5, 1),
(68, 'B6', 'Beban SKS per semester sudah proporsional.', NULL, 'skala', 'kompetensi', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 6, 1),
(69, 'B7', 'Kurikulum memberi ruang yang cukup bagi mahasiswa untuk mendalami minat melalui mata kuliah pilihan.', NULL, 'skala', 'kompetensi', 'dosen', 1, '[\"Sangat tidak setuju\", \"Tidak setuju\", \"Netral\", \"Setuju\", \"Sangat setuju\"]', NULL, NULL, NULL, 7, 1),
(70, 'B8', 'Bidang apa yang sebaiknya diperkuat dalam kurikulum?', NULL, 'pilihan_ganda_banyak', 'kompetensi', 'dosen', 1, NULL, NULL, NULL, 2, 8, 1),
(71, 'B9', 'Usulan mata kuliah baru atau perubahan struktur kurikulum.', NULL, 'teks', 'kompetensi', 'dosen', 0, NULL, NULL, NULL, NULL, 9, 1),
(72, 'B10', 'Saran lain untuk kurikulum program studi.', NULL, 'teks', 'kompetensi', 'dosen', 0, NULL, NULL, NULL, NULL, 10, 1);

INSERT INTO opsi_pertanyaan (id, pertanyaan_id, teks_opsi, kategori_kompetensi_id, urutan) VALUES
(1, 18, 'Perlu diperdalam', NULL, 1),
(2, 18, 'Sudah sesuai', NULL, 2),
(3, 18, 'Cukup sebagai pengantar', NULL, 3),
(4, 18, 'Tidak lagi diperlukan', NULL, 4),
(5, 21, 'Sudah sesuai; cukup 1 semester dengan bobot SKS saat ini', NULL, 1),
(6, 21, 'Bobot SKS perlu ditambah', NULL, 2),
(7, 21, 'Bobot SKS perlu dikurangi', NULL, 3),
(8, 21, 'Sebaiknya diperpanjang menjadi 2 semester (dasar dan lanjutan)', NULL, 4),
(9, 26, 'Sebaiknya lebih awal', NULL, 1),
(10, 26, 'Sudah tepat', NULL, 2),
(11, 26, 'Sebaiknya lebih akhir', NULL, 3),
(12, 27, 'Sebaiknya lebih awal', NULL, 1),
(13, 27, 'Sudah tepat', NULL, 2),
(14, 27, 'Sebaiknya lebih akhir', NULL, 3),
(15, 28, 'Sebaiknya lebih awal', NULL, 1),
(16, 28, 'Sudah tepat', NULL, 2),
(17, 28, 'Sebaiknya lebih akhir', NULL, 3),
(18, 29, 'Tetap wajib', NULL, 1),
(19, 29, 'Dijadikan pilihan', NULL, 2),
(20, 29, 'Digabung dengan mata kuliah lain', NULL, 3),
(21, 29, 'Dihentikan', NULL, 4),
(22, 30, 'Tetap wajib', NULL, 1),
(23, 30, 'Dijadikan pilihan', NULL, 2),
(24, 30, 'Digabung dengan mata kuliah lain', NULL, 3),
(25, 30, 'Dihentikan', NULL, 4),
(26, 31, 'Tetap wajib', NULL, 1),
(27, 31, 'Dijadikan pilihan', NULL, 2),
(28, 31, 'Digabung dengan mata kuliah lain', NULL, 3),
(29, 31, 'Dihentikan', NULL, 4),
(30, 32, 'Tetap wajib', NULL, 1),
(31, 32, 'Dijadikan pilihan', NULL, 2),
(32, 32, 'Digabung dengan mata kuliah lain', NULL, 3),
(33, 32, 'Dihentikan', NULL, 4),
(34, 40, 'K1 Data, Analitik & Kecerdasan Buatan', 1, 1),
(35, 40, 'K2 Enterprise Systems & Transformasi Bisnis', 2, 2),
(36, 40, 'K3 Rekayasa Perangkat Lunak & Pengembangan Aplikasi', 3, 3),
(37, 40, 'K4 Infrastruktur, Jaringan & Keamanan Siber', 4, 4),
(38, 40, 'K5 Manajemen Proyek, Tata Kelola & Audit TI', 5, 5),
(39, 49, 'K1 Data, Analitik & Kecerdasan Buatan', 1, 1),
(40, 49, 'K2 Enterprise Systems & Transformasi Bisnis', 2, 2),
(41, 49, 'K3 Rekayasa Perangkat Lunak & Pengembangan Aplikasi', 3, 3),
(42, 49, 'K4 Infrastruktur, Jaringan & Keamanan Siber', 4, 4),
(43, 49, 'K5 Manajemen Proyek, Tata Kelola & Audit TI', 5, 5),
(44, 59, 'K1 Data, Analitik & Kecerdasan Buatan', 1, 1),
(45, 59, 'K2 Enterprise Systems & Transformasi Bisnis', 2, 2),
(46, 59, 'K3 Rekayasa Perangkat Lunak & Pengembangan Aplikasi', 3, 3),
(47, 59, 'K4 Infrastruktur, Jaringan & Keamanan Siber', 4, 4),
(48, 59, 'K5 Manajemen Proyek, Tata Kelola & Audit TI', 5, 5),
(49, 70, 'K1 Data, Analitik & Kecerdasan Buatan', 1, 1),
(50, 70, 'K2 Enterprise Systems & Transformasi Bisnis', 2, 2),
(51, 70, 'K3 Rekayasa Perangkat Lunak & Pengembangan Aplikasi', 3, 3),
(52, 70, 'K4 Infrastruktur, Jaringan & Keamanan Siber', 4, 4),
(53, 70, 'K5 Manajemen Proyek, Tata Kelola & Audit TI', 5, 5);

-- Dummy Answers Data
INSERT INTO pengisian (id, pengguna_id, periode_id, status, tab_terakhir, terakhir_disimpan, waktu_submit) VALUES
(1, 2, 1, 'final', 2, '2025-06-01 10:30:00', '2025-06-01 10:30:00'),
(2, 11, 1, 'final', 2, '2025-06-02 11:20:00', '2025-06-02 11:20:00'),
(3, 14, 1, 'final', 2, '2025-06-03 14:45:00', '2025-06-03 14:45:00'),
(4, 6, 1, 'final', 2, '2025-06-04 09:15:00', '2025-06-04 09:15:00'),
(5, 2, 2, 'final', 2, '2025-10-01 08:30:00', '2025-10-01 08:30:00'),
(6, 3, 2, 'final', 2, '2025-10-02 09:30:00', '2025-10-02 09:30:00'),
(7, 10, 2, 'final', 2, '2025-10-03 10:20:00', '2025-10-03 10:20:00'),
(8, 15, 2, 'final', 2, '2025-10-04 11:45:00', '2025-10-04 11:45:00'),
(9, 7, 2, 'final', 2, '2025-10-05 13:15:00', '2025-10-05 13:15:00');

INSERT INTO pengisian_matkul (pengisian_id, mata_kuliah_id) VALUES
(1, 1), (1, 2), (1, 3),
(2, 4), (2, 5),
(3, 6), (3, 7),
(4, 8), (4, 9),
(5, 10), (5, 11), (5, 12),
(6, 13), (6, 14),
(7, 15), (7, 16),
(8, 17), (8, 18),
(9, 19), (9, 20);

INSERT INTO jawaban (id, pengisian_id, pertanyaan_id, mata_kuliah_id, nilai_skala, opsi_id, teks, alasan) VALUES
(1, 1, 1, 1, 4, NULL, NULL, NULL),
(2, 1, 2, 1, 4, NULL, NULL, NULL),
(3, 1, 1, 2, 3, NULL, NULL, NULL),
(4, 1, 2, 2, 5, NULL, NULL, NULL),
(5, 1, 1, 3, 4, NULL, NULL, NULL),
(6, 1, 2, 3, 4, NULL, NULL, NULL),
(7, 2, 7, 4, 3, NULL, NULL, NULL),
(8, 2, 8, 4, 3, NULL, NULL, NULL),
(9, 2, 7, 5, 3, NULL, NULL, NULL),
(10, 2, 8, 5, 3, NULL, NULL, NULL),
(11, 3, 13, 6, 3, NULL, NULL, NULL),
(12, 3, 14, 6, 4, NULL, NULL, NULL),
(13, 3, 13, 7, 5, NULL, NULL, NULL),
(14, 3, 14, 7, 5, NULL, NULL, NULL),
(15, 4, 19, 8, 4, NULL, NULL, NULL),
(16, 4, 20, 8, 3, NULL, NULL, NULL),
(17, 4, 19, 9, 5, NULL, NULL, NULL),
(18, 4, 20, 9, 4, NULL, NULL, NULL),
(19, 5, 1, 10, 3, NULL, NULL, NULL),
(20, 5, 2, 10, 4, NULL, NULL, NULL),
(21, 5, 1, 11, 5, NULL, NULL, NULL),
(22, 5, 2, 11, 5, NULL, NULL, NULL),
(23, 5, 1, 12, 5, NULL, NULL, NULL),
(24, 5, 2, 12, 4, NULL, NULL, NULL),
(25, 6, 1, 13, 4, NULL, NULL, NULL),
(26, 6, 2, 13, 4, NULL, NULL, NULL),
(27, 6, 1, 14, 4, NULL, NULL, NULL),
(28, 6, 2, 14, 3, NULL, NULL, NULL),
(29, 7, 7, 15, 3, NULL, NULL, NULL),
(30, 7, 8, 15, 3, NULL, NULL, NULL),
(31, 7, 7, 16, 5, NULL, NULL, NULL),
(32, 7, 8, 16, 4, NULL, NULL, NULL),
(33, 8, 13, 17, 4, NULL, NULL, NULL),
(34, 8, 14, 17, 4, NULL, NULL, NULL),
(35, 8, 13, 18, 5, NULL, NULL, NULL),
(36, 8, 14, 18, 4, NULL, NULL, NULL),
(37, 9, 19, 19, 3, NULL, NULL, NULL),
(38, 9, 20, 19, 3, NULL, NULL, NULL),
(39, 9, 19, 20, 5, NULL, NULL, NULL),
(40, 9, 20, 20, 4, NULL, NULL, NULL);

